name: servering
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: check pwd
        run: |
          pwd
      - name: Running Discord
        run: |
          pip install -r requirements.txt
          pip install -U discord==1.7.3 pip install -U discord.py==1.7.3 
          python3 main.py
      - name: Done! Running server 8 jam
        run: |
          ping google.com -t
